apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connect-metrics
  namespace: debezium
data:
  metrics-config.yml: |
    # Based on official Strimzi example:
    # https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/metrics/kafka-connect-metrics.yaml
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
      # Kafka Connect worker metrics
      - pattern: kafka.connect<type=connect-worker-metrics><>([a-z-]+-total)
        name: kafka_connect_worker_$1
        help: "Kafka Connect JMX metric worker"
        type: COUNTER
      - pattern: kafka.connect<type=connect-worker-metrics><>([a-z-]+)
        name: kafka_connect_worker_$1
        help: "Kafka Connect JMX metric worker"
        type: GAUGE

      # Kafka Connect worker metrics per connector
      - pattern: kafka.connect<type=connect-worker-metrics, connector=(.+)><>([a-z-]+)
        name: kafka_connect_worker_$2
        labels:
          connector: "$1"
        help: "Kafka Connect JMX metric $1"
        type: GAUGE

      # Connector task metrics
      - pattern: kafka.connect<type=(.+)-metrics, connector=(.+), task=(.+)><>(.+-total)
        name: kafka_connect_$1_$4
        labels:
          connector: "$2"
          task: "$3"
        help: "Kafka Connect JMX metric type $1"
        type: COUNTER
      - pattern: kafka.connect<type=(.+)-metrics, connector=(.+), task=(.+)><>(.+-count|.+-ms|.+-ratio|.+-rate|.+-max|.+-avg|.+-failures|.+-errors|.+-retries|.+-skipped)
        name: kafka_connect_$1_$4
        labels:
          connector: "$2"
          task: "$3"
        help: "Kafka Connect JMX metric type $1"
        type: GAUGE

      # Connector task status
      - pattern: 'kafka.connect<type=connector-task-metrics, connector=(.+), task=(.+)><>status: ([a-z-]+)'
        name: kafka_connect_connector_task_status
        value: 1
        labels:
          connector: "$1"
          task: "$2"
          status: "$3"
        help: "Kafka Connect JMX Connector task status"
        type: GAUGE

      # Worker rebalance metrics
      - pattern: kafka.connect<type=connect-worker-rebalance-metrics><>([a-z-]+-total)
        name: kafka_connect_worker_rebalance_$1
        help: "Kafka Connect JMX metric rebalance information"
        type: COUNTER
      - pattern: kafka.connect<type=connect-worker-rebalance-metrics><>([a-z-]+)
        name: kafka_connect_worker_rebalance_$1
        help: "Kafka Connect JMX metric rebalance information"
        type: GAUGE

      # Coordinator metrics
      - pattern: kafka.connect<type=connect-coordinator-metrics><>(assigned-connectors|assigned-tasks)
        name: kafka_connect_coordinator_$1
        help: "Kafka Connect JMX metric assignment information"
        type: GAUGE
