apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 1h
  chart:
    spec:
      chart: sealed-secrets
      version: "2.16.2"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: sealed-secrets
  values:
    fullnameOverride: sealed-secrets-controller
