apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: ">=5.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: loki
      interval: 1h
  values:
    loki:
      auth_enabled: false
    singleBinary:
      replicas: 1
