apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: ">=6.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: loki
      interval: 1h
  values:
    # Deployment mode - configures gateway and all components for single binary
    deploymentMode: SingleBinary
    loki:
      # Set to true for multi-tenancy (requires X-Scope-OrgID header)
      auth_enabled: false
      # Storage schema configuration
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
      # Use local filesystem storage (not S3/GCS/Azure)
      storage:
        type: filesystem
      # Retention - auto-delete logs after 24 hours
      limits_config:
        retention_period: 24h
      # Single replica with inmemory kvstore for dev
      commonConfig:
        replication_factor: 1
        ring:
          kvstore:
            store: inmemory
      # Compactor handles log deletion
      compactor:
        retention_enabled: true
        delete_request_store: filesystem
        working_directory: /var/loki/compactor
        compaction_interval: 10m
    # Use single binary mode (not distributed)
    singleBinary:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          memory: 2Gi
    # Disable distributed components
    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0
    # Disable anti-affinity for single-node development cluster
    gateway:
      affinity: {}
    # Disable caching (not needed for dev, saves memory)
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    # Disable extra components for dev
    lokiCanary:
      enabled: false
    test:
      enabled: false
    monitoring:
      selfMonitoring:
        enabled: false
      lokiCanary:
        enabled: false
